/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jc_bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Cláudio
 */
public class ContaDiretor extends javax.swing.JFrame {

    /**
     * Creates new form ContaDiretor
     */
    public ContaDiretor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saldo = new javax.swing.JButton();
        saque = new javax.swing.JButton();
        deposito = new javax.swing.JButton();
        emprestimo = new javax.swing.JButton();
        limite = new javax.swing.JButton();
        extrato = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        criaContaFun = new javax.swing.JButton();
        realizaEmprestimoFun = new javax.swing.JButton();
        verContasFun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        saldo.setText("SALDO");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        saque.setText("SAQUE");
        saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saqueActionPerformed(evt);
            }
        });

        deposito.setText("DEPOSITO");
        deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoActionPerformed(evt);
            }
        });

        emprestimo.setText("EMPRESTIMO");
        emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoActionPerformed(evt);
            }
        });

        limite.setText("LIMITE");
        limite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiteActionPerformed(evt);
            }
        });

        extrato.setText("EXTRATO");
        extrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extratoActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 51, 0));
        jButton7.setText("SAIR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        criaContaFun.setText("CADASTRA FUNCIONÁRIO");
        criaContaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaContaFunActionPerformed(evt);
            }
        });

        realizaEmprestimoFun.setText("EMPRESTIMO FUNCIONÁRIO");
        realizaEmprestimoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaEmprestimoFunActionPerformed(evt);
            }
        });

        verContasFun.setText("VER CONTAS");
        verContasFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verContasFunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(156, 156, 156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(limite, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(deposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(emprestimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(realizaEmprestimoFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verContasFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(criaContaFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(extrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldo)
                    .addComponent(criaContaFun))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(saque)
                        .addGap(18, 18, 18)
                        .addComponent(deposito)
                        .addGap(18, 18, 18)
                        .addComponent(limite))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(realizaEmprestimoFun)
                        .addGap(31, 31, 31)
                        .addComponent(verContasFun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emprestimo)
                    .addComponent(extrato))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueActionPerformed
        
        JOptionPane.showMessageDialog(null,"Seu saldo em conta é : 12.000.00");
    }//GEN-LAST:event_saqueActionPerformed

    private void limiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueActionPerformed
        
        JOptionPane.showMessageDialog(null,"Seu saldo em conta é : 25.000.00");
    }//GEN-LAST:event_saqueActionPerformed
    
    private void emprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoActionPerformed
        
        new Emprestimo().setVisible(true);
    }//GEN-LAST:event_emprestimoActionPerformed


    private void saqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saqueActionPerformed
        
        new Saque().setVisible(true);
    }//GEN-LAST:event_saqueActionPerformed

    private void depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoActionPerformed
        
        new Deposito().setVisible(true);
    }//GEN-LAST:event_depositoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void criaContaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaContaFunActionPerformed
      
        new Cadastro().setVisible(true);
    }//GEN-LAST:event_criaContaFunActionPerformed

    private void extratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaContaFunActionPerformed
        
        JOptionPane.showMessageDialog(null," CONTA : 45675764 \n SALDO : 1.200.00 \n LIMITE : 2.300.00 \n USUÁRIO : CLÁUDIO \n SAQUE : 200.00 \n DEPOSITO: 0.0 ");
        this.dispose();
        
    }//GEN-LAST:event_criaContaFunActionPerformed

    private void realizaEmprestimoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaEmprestimoFunActionPerformed
       
        new EmprestimoFuncionario().setVisible(true);
    }//GEN-LAST:event_realizaEmprestimoFunActionPerformed

    private void verContasFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaEmprestimoFunActionPerformed
        JOptionPane.showMessageDialog(null,"| tipo de conta | nome   | número   | saldo   | limite   | emprestimo  | \n1---	corrente---	joana---silva---	1q2w---	não---	345.876.456-40--- Caixa  \n2---corrente---lucas---silva---002w---não	---945.765.456-40---secretário \n3---corrente---gabriel---costa---067w---sim---789.765.456-40---caixa \n4---corrente---carlos---costa---2w35---sim---321.678.456-40---caixa \n5---especial---daniel---costa---ty35---sim---321.678.456-40---gerente \n6---especial---gustavo---silva---tre4---sim---321.543.456-40---diretor \n7---corrente---joão---silva---27756---não---345.654.456-40---secretário" );
  

        Conexao bd = new Conexao();
        bd.consultarContasPoupanca();
        bd.consultarContasCorrente();

        JOptionPane.showMessageDialog(null,"| tipo de conta | nome   | número   | saldo   | limite   | emprestimo  | \n\n |  corrente   |   João     | 34256543 | 200.00 | 800.00 | 32.000.00 | \n |  corrente   | daniel | 89256543 | 700.00 | 400.00 | 2.000.00 | \n | poupança | flávio | 34257676 | 10.00 | 900.00 | 4.000.00 | \n | poupança | João | 90876534 | 23.000.00 | 800.00 | 00.00 | \n | poupança | eduardo | 89256543 | 1200.00 | 1800.00 | 9.000.00 | \n | poupança |  rafael   | 76859403 | 1200.00 | 1800.00 | 2.000.00 | \n |   corrente  | natanael | 12656543 | 2.400.00 | 3800.00 | 6.000.00 | ");
        this.dispose();
    }//GEN-LAST:event_realizaEmprestimoFunActionPerformed\n

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaDiretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criaContaFun;
    private javax.swing.JButton deposito;
    private javax.swing.JButton emprestimo;
    private javax.swing.JButton extrato;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limite;
    private javax.swing.JButton realizaEmprestimoFun;
    private javax.swing.JButton saldo;
    private javax.swing.JButton saque;
    private javax.swing.JButton verContasFun;
    // End of variables declaration//GEN-END:variables
}
